### ISSUE TITLE
Translate option

### ISSUE THREAD

**Issue by ewertr** [CensoredUsername/unrpyc#100]
Having trouble figuring out how to make use of the -t option for translating while decompiling.
I have a game that splits it translations into lots of different files. I used unrpyc to decompile all the English translation files then used 'cat * > english.rpy' to combine them into one. However using the -t option with that file results in all files failing to decompile with this stacktrace for each one:
`Traceback (most recent call last):
  File ".\unrpyc-1.1.3\unrpyc.py", line 160, in worker
    translator.language, translator.dialogue, translator.strings = magic.loads(args.translations, class_factory)
  File ".\unrpyc-1.1.3\decompiler\magic.py", line 560, in loads
    encoding=encoding, errors=errors).load()
  File "c:\Python27\lib\pickle.py", line 864, in load
    dispatch[key](self)
KeyError: '\n'`

**Comment by jackmcbarn** [comment]
You don't need to manually combine any files. Just do `./unrpyc.py -T translations.pkl` then `./unrpyc.py -t translations.pkl`. If this still doesn't work, then please tell us what game this is so we can try it ourselves.

**Comment by jackmcbarn** [comment]
Closing due to lack of response.
