### ISSUE TITLE
ATL statement contains two expressions in a row; is one of them a misspelled property? If not, separate them with pass.

### ISSUE THREAD

**Issue by ZeRetr0** [CensoredUsername/unrpyc#101]
Hello, I've tried to decompile script.rpyc from Innocent Witches 5.1F and get an error(error.txt). I use the latest version 1.1.4 of unrpyc.
[error.zip](https://github.com/CensoredUsername/unrpyc/files/5457525/error.zip)

**Comment by jackmcbarn** [comment]
Try [the `innocent_witches` branch](https://github.com/CensoredUsername/unrpyc/tree/innocent_witches) with the changes I just made today.

**Comment by ZeRetr0** [comment]
> Try [the `innocent_witches` branch](https://github.com/CensoredUsername/unrpyc/tree/innocent_witches) with the changes I just made today.

Thanks, it works
