### ISSUE TITLE
Release 1.1.5

### ISSUE THREAD

**Issue by CensoredUsername** [CensoredUsername/unrpyc#105]
There's a bunch of stuff on the dev branch. We should probably do a release / merge to master some time

@jackmcbarn you've added a bunch of stuff there as well, is everything ready for merge?

**Comment by jackmcbarn** [comment]
I've been using it here and there and nothing seems broken, so I think so.

**Comment by madeddy** [comment]
Will this bring unrpyc up to date with all the changes(and hickups...) of the last ~1.5 years and the new v7.4  of RenPy?

**Comment by CensoredUsername** [comment]
@madeddy I have no idea. I don't do a lot of digging into VNs myself these days and don't keep up with ren'py patch notes, I maintain unrpyc as i find reverse engineering enjoyable. If people make issues (with test cases that I can work with) correctly I'll gladly fix them. If there are none I assume everything still works, if it isn't but people don't inform me then it won't get fixed ¯\_(ツ)_/¯.

**Comment by madeddy** [comment]
I can relate to this. I am somewhat of the same and figuring such stuff out, however you're in advantage there because i am not this far in coding experience.

As for issues, I will report them if I find or see something... and v7.4.0 is really new, so i expect it will take time for the hidden traps to show themself. 
Cheerio

**Comment by jackmcbarn** [comment]
You can easily verify the result of any decompilation: dump the original .rpyc to a .txt with the `-d --comparable` flags, then decompile, delete the .rpyc, and recompile, and then dump the new .rpyc the same way and see if it's identical.

**Comment by madeddy** [comment]
Thats actually a nice trick. Will remember. Thanks

**Comment by CensoredUsername** [comment]
Released v1.1.5
