### ISSUE TITLE
news rpyc that i can´t decompile

### ISSUE THREAD

**Issue by paloslios** [CensoredUsername/unrpyc#109]
I can't decompile rpyc
of the latest version of Oopsy Daisy that uses renpy 7.4.0. see if you can do something greetings

**Comment by CensoredUsername** [comment]
Please actually upload a sample rpyc file that I can work with to test.

**Comment by paloslios** [comment]
[screens.zip](https://github.com/CensoredUsername/unrpyc/files/5803883/screens.zip)

thank you

**Comment by CensoredUsername** [comment]
Fixed on dev! It was some pretty minor stuff luckily. Please test if this works for all your files and then close the issue.

**Comment by paloslios** [comment]
sorry... but i don´t understand

**Comment by paloslios** [comment]
i don´t found dev

**Comment by CensoredUsername** [comment]
It's referring to the dev branch of the repository. https://github.com/CensoredUsername/unrpyc/tree/dev

**Comment by paloslios** [comment]
many thanks
I had a hard time understanding how to make the program work but in the end I got it
Thanks a lot
