### ISSUE TITLE
Minor: Unused func in deobfuscate.py has small bugs

### ISSUE THREAD

**Issue by madeddy** [CensoredUsername/unrpyc#114]
Don't know if the function ever sees use, but reporting my find for completeness and to save time:

- `header` in Line 236 and `header_data` in 239 should have the same name.
- `raw_contents` in LIne 259 is nowhere defined. Misses perhaps a `raw_contents = f.read()` ?
- `diagnosis = []` is unused

**Comment by CensoredUsername** [comment]
Thanks for the note, I'll fix that when that function actually ends up being used (idea was to do this check, then if it fails try to use deobfuscation strategies, but I didn't get there yet).

**Comment by CensoredUsername** [comment]
Fix'd
