### ISSUE TITLE
New rpyc files that I cannot decompile

### ISSUE THREAD

**Issue by pratikpatel8982** [CensoredUsername/unrpyc#117]
Hi these are the two files that I cannot decompile. Both of them come from two different developers.
Here is the link: [Custom RPYC](https://mega.nz/file/6kdknJpJ#eFcw86iyR-E2fNrrXYKqGq6t3iX5CafvB9eRGuVHOYs) 
Plz help. Thank you.

**Comment by madeddy** [comment]
RTFM... 
One try with the use of the additional deobfuscation switch and it worked like a charm on your files. *Really.*
