### ISSUE TITLE
common.rpyc

### ISSUE THREAD

**Issue by corona57** [CensoredUsername/unrpyc#120]
[common.zip](https://github.com/CensoredUsername/unrpyc/files/6287620/common.zip)

Unable to open common.rpyc. help me! oh

**Comment by CensoredUsername** [comment]
Please provide additional information as requested in the [README](https://github.com/CensoredUsername/unrpyc#issue-reports)

**Comment by corona57** [comment]
> [common.zip](https://github.com/CensoredUsername/unrpyc/files/6287620/common.zip)
> 
> Common.rpyc açılamıyor. bana yardım et! oh

![Ekran Görüntüsü (36)](https://user-images.githubusercontent.com/82233551/114233815-920e2500-9986-11eb-8271-a41c9234746d.png)

**Comment by madeddy** [comment]
The developer manipulated the rpyc file format so decompiling isn't easily possible like we see here. 

Please provide if possible the name of the game/developer and from the games directory the file ".../your_games_path/renpy/script.py".

**Comment by CensoredUsername** [comment]
File is pretty damn mangled. Entire thing is base64-encoded from a cursory look can you confirm that bytecode.rpyb also doens't work?

**Comment by corona57** [comment]
I don't know how to run bytecode.rpyb. I don't have such a file.

**Comment by corona57** [comment]
bytecode.rpyb in the file does not exist.

**Comment by madeddy** [comment]
> bytecode.rpyb in the file does not exist.

No. You do not understand what @CensoredUsername  say'd. I don't believe it. RTFM dammit! 

There is a second way to decompile game files and it IS clearly described in the _readme_ for _unrpyc_. But to understand this you **need to read** the information actually: https://github.com/CensoredUsername/unrpyc#game-injection

**Comment by corona57** [comment]
hmm understand thanks.

**Comment by corona57** [comment]
I did what you said but it still did not open.

**Comment by CensoredUsername** [comment]
Seems that whoever made this file used some non-trivial obfuscation, it's not too hard to break if you know some python reverse engineering (you can just rip the data straight out of the engine with some tools), but I have no interest in figuring it out myself as it won't be significantly portable to other games.

**Comment by corona57** [comment]
I don't know reverse engineering. Believe me, if you make a video narration, people will be delighted .... for example on your youtube channel.

**Comment by CensoredUsername** [comment]
Here's the thing. reverse engineering isn't a process, it's a skill. Someone is trying to hide something from you, and you have to figure out how they did that so you can uncover it. But, the moment you publish this they have access to this solution as well and they can find a different way of hiding it, rendering all the published data moot. This means that the only way to break things effectively is to keep your approach secret.

I'm only interested in the public usability of this tool, so have little interest in that. There's a bunch of attacks that I know would easily work, but I can also think of ways to guard against them. So you need to be able to modify these attacks, and understand how they work. A youtube tutorial won't teach you understanding of programming and reverse engineering. You'll have to figure out how to get the data out of the engine on your own (or get someone to do that for you) and not publish it until it's broken for it to stay useful. Then, you can still use this tool to decompile it back to normal script files.

**Comment by madeddy** [comment]
I also asked [two days ago](https://github.com/CensoredUsername/unrpyc/issues/120#issuecomment-816986484) for more information with wich we can work but you did not give them. More info gives us possibly a better view on the problem. Sometimes its just one little detail and without it nobody can help.

**Comment by corona57** [comment]
after all there is an rpyc file and the program you did it cannot open. So this program is useless trash.

**Comment by CensoredUsername** [comment]
I do not make any claims of supporting anything but stock ren'py, which this file is most assuredly not. You're free to modify it yourself to figure out that support, for which all code is available already. Insults are however not tolerated here, so this discussion is over.
