### ISSUE TITLE
setup.py doesn't copy required decompile.py script

### ISSUE THREAD

**Issue by einstein95** [CensoredUsername/unrpyc#121]
Using WSL, OS deets:
```
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal
```
Installed with `sudo python2 setup.py install`, got error when decompiling a script:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/unrpyc-0.1-py2.7.egg/unrpyc.py", line 104, in <module>
    import deobfuscate
ImportError: No module named deobfuscate
```
Fixed with `sudo cp deobfuscate.py* /usr/local/lib/python2.7/dist-packages/unrpyc-0.1-py2.7.egg/`
May have to do with `deobfuscate.py` not being listed on this line? https://github.com/CensoredUsername/unrpyc/blob/8edfc2711e7105c1ab3a1a25d1c3264b8a55cc16/setup.py#L15

**Comment by madeddy** [comment]
Yes, thats not up to date, so i would recommend not to use it. Why installing anyway. Just download the last release and start it from the unpack-dir e.g. `python2 ...your-path/unpack/unrpyc.py -cobber <targetdir>`

General note: The half done travis and setup stuff should be removed imo. At least in _main_ branch.

**Comment by CensoredUsername** [comment]
@madeddy I appreciate the help, but as maintainer this is just an issue that should be fixed, installing python scripts is quite a normal action. The setup script ought to be operational. I'd simply forgotten to update it.

In the meantime, the suggested workaround does indeed work. Thanks for the issue report!

**Comment by CensoredUsername** [comment]
Fixed on `dev`.
