### ISSUE TITLE
unrpyc.py: error: too few arguments

### ISSUE THREAD

**Issue by helzing** [CensoredUsername/unrpyc#124]
![Ekran Görüntüsü (37)](https://user-images.githubusercontent.com/76672047/118143552-264f2a00-b414-11eb-9678-2510a37cfcac.png)

how can i fix this error.

**Comment by CensoredUsername** [comment]
huh, running that command on my box (`py -2 unrpyc.py folder_containing_rpyc_files --try-harder`) works just fine. The error is also originating from the argparse module itself, it's the error you get when too little positional arguments are present, but there's clearly the `game` folder there.

I have no idea what's happening there, sorry.

**Comment by helzing** [comment]
It was working before. A different version of python has been installed.

**Comment by helzing** [comment]
I am deleting and loading it from the beginning, it does not happen.

**Comment by CensoredUsername** [comment]
I take this is fixed then? Otherwise please provide additional info like operating system, python version used, etc.

**Comment by helzing** [comment]
I fixed it by formatting my pc.

________________________________
Gönderen: CensoredUsername ***@***.***>
Gönderildi: 16 Mayıs 2021 Pazar 01:32
Kime: CensoredUsername/unrpyc ***@***.***>
Bilgi: helzing ***@***.***>; Author ***@***.***>
Konu: Re: [CensoredUsername/unrpyc] unrpyc.py: error: too few arguments (#124)


I take this is fixed then? Otherwise please provide additional info like operating system, python version used, etc.

**Comment by helzing** [comment]
Python versions intertwined

________________________________
Gönderen: CensoredUsername ***@***.***>
Gönderildi: 16 Mayıs 2021 Pazar 01:32
Kime: CensoredUsername/unrpyc ***@***.***>
Bilgi: helzing ***@***.***>; Author ***@***.***>
Konu: Re: [CensoredUsername/unrpyc] unrpyc.py: error: too few arguments (#124)


I take this is fixed then? Otherwise please provide additional info like operating system, python version used, etc.
