### ISSUE TITLE
expected statement

### ISSUE THREAD

**Issue by tooyangtoonaive** [CensoredUsername/unrpyc#129]
such as:
File "game/core/screens/graph_anim.rpy", line 14: end of line expected.
    at transform:crop (0, 0, 0, config.screen_height)
                 ^

File "game/defines/places/hot_springs/first_floor.rpy", line 69: expected statement.
    place place_hot_springs_first_floor
                                       ^

attachfile:
[py.zip](https://github.com/CensoredUsername/unrpyc/files/7147401/py.zip)

**Comment by CensoredUsername** [comment]
Seems like some stuff is being placed at the wrong line. I'll can look into it when I have time, but if you want to, the offending code is at https://github.com/CensoredUsername/unrpyc/blob/8edfc2711e7105c1ab3a1a25d1c3264b8a55cc16/decompiler/sl2decompiler.py#L365-L374

**Comment by CensoredUsername** [comment]
probably related to #115

**Comment by CensoredUsername** [comment]
The first should be fixed thanks to the SL2 keywords and children rewrite, as well as da61f2e (apparently nobody uses the transform displayable so we didn't know about that before. The latter `expected statement` issue isn't a unrpyc issue. The file records a renpy `UserStatement` with the name `place` which was likely defined in another .rpy[c] file.

**Comment by CensoredUsername** [comment]
Should be fixed in the current release (1.2.0), please reopen if it isn't.
