### ISSUE TITLE
Error while using cmd

### ISSUE THREAD

**Issue by Ruttie2006** [CensoredUsername/unrpyc#131]
I'm getting an error when using the tool via command line, I put the `un.rypc` file next to the other `.rypc` files.
When I run `py un.rpyc --help` while targeting the dir with the file I get this error:
```
    x�loads
          ^
SyntaxError: (unicode error) 'utf-8' codec can't decode byte 0xda in position 1: invalid continuation byte
```
Could anyone help?   

Extra info:
Used version: Latest ([1.1.6](https://github.com/CensoredUsername/unrpyc/releases/tag/v1.1.6)).
Python version: `-3.10-64 *`
Command: `py un.rpyc --help`.
Intent: Get the helper for the program.

It appears it already crashes in the first line, leading me to believe something is wrong on my side, but I can't figure out what...
Any help would be much appreciated!

**Comment by madeddy** [comment]
> Python version: `-3.10-64 *`

I could be wrong, but i think such errors are happening if users don't read the instructions careful enough or not at all. See for reference: https://github.com/CensoredUsername/unrpyc#usage

**Python 2.7** required!  :smirk:
This should do it. Good luck.

**Comment by Dobby233Liu** [comment]
> `py un.rpyc --help`

You dropped a un.rpyc in the game? Then just run the game, it will automatically decompile the scripts.
