### ISSUE TITLE
Linux support. (suggestion)

### ISSUE THREAD

**Issue by nicker7** [CensoredUsername/unrpyc#132]
You could make the tool work with the .sh executable, so I wouldn't need to emulate Windows since I need to extract text from the game I intend to translate, and I do it all without leaving linux.

**Comment by CensoredUsername** [comment]
I'm confused, I don't recall there being any OS dependency in the script to begin with. Does it not work on Linux right now?

**Comment by nicker7** [comment]
Sorry, I didn't know I had to listen to the game through the terminal for the tool to work.

Since I always create an executable for it in Cinnamon's menu, simplifying things for me.

But through the terminal it worked.

Thank you very much.
