### ISSUE TITLE
Error while decompiling .rpyc

### ISSUE THREAD

**Issue by mattmurdock12** [CensoredUsername/unrpyc#133]
[renpy.zip](https://github.com/CensoredUsername/unrpyc/files/7532854/renpy.zip)

Hello, I have a new problem.
I added the renpy folder, I can't convert files from .rpyc to .rpy. And I can't open .rpa archive.
please help :) @CensoredUsername

**Comment by CensoredUsername** [comment]
Please follow the issue reporting instructions in the README, it'll make the process a bit easier.

**Comment by CensoredUsername** [comment]
Closing due to lack of response

**Comment by TzTcTT** [comment]
Hello! How to solve this mistake?
1，D:\unrpyc-master>py unrpyc.py -c D:\unrpyc-master\work\*                                                        \*
Decompiling D:\unrpyc-master\work\screens.rpyc to D:\unrpyc-master\work\screens.rpy...
Error while decompiling D:\unrpyc-master\work\screens.rpyc:
Traceback (most recent call last):
  File "D:\unrpyc-master\unrpyc.py", line 194, in worker
    tag_outside_block=args.tag_outside_block, init_offset=args.init_offset, try_harder=args.try_harder)
  File "D:\unrpyc-master\unrpyc.py", line 157, in decompile_rpyc
    ast = read_ast_from_file(in_file)
  File "D:\unrpyc-master\unrpyc.py", line 123, in read_ast_from_file
    raw_contents = chunks[1]
KeyError: 1

Decompilation of 1 file failed

2，Decompiling D:\unrpyc-master\work\screens.rpyc to D:\unrpyc-master\work\screens.rpy...
Error while decompiling D:\unrpyc-master\work\screens.rpyc:
Traceback (most recent call last):
  File "D:\unrpyc-master\unrpyc.py", line 194, in worker
    tag_outside_block=args.tag_outside_block, init_offset=args.init_offset, try_harder=args.try_harder)
  File "D:\unrpyc-master\unrpyc.py", line 157, in decompile_rpyc
    ast = read_ast_from_file(in_file)
  File "D:\unrpyc-master\unrpyc.py", line 125, in read_ast_from_file
    raw_contents = raw_contents.decode('zlib')
  File "D:\Python2.7\lib\encodings\zlib_codec.py", line 43, in zlib_decode
    output = zlib.decompress(input)
error: Error -3 while decompressing data: incorrect header check

Decompilation of 1 file failed
