### ISSUE TITLE
Python 3 - AttributeError: 'Return' object has no attribute 'linenumber'

### ISSUE THREAD

**Issue by Bexa2** [CensoredUsername/unrpyc#137]
This should be a options.rpyc
[options.zip](https://github.com/CensoredUsername/unrpyc/files/7970389/options.zip)

```python
Traceback (most recent call last):
  File ".\normalize_paths.py", line 123, in <module>
    main()
  File ".\normalize_paths.py", line 119, in main
    (name, version) = get_name_and_version(renpy_path)
  File ".\normalize_paths.py", line 68, in get_name_and_version
    if not unrpyc.decompile_rpyc(tmp_filename):
  File "G:\games_test\rpa_decompiler\unrpyc.py", line 166, in decompile_rpyc
    decompiler.pprint(out_file, ast, decompile_python=decompile_python, printlock=printlock,
  File "G:\games_test\rpa_decompiler\decompiler\__init__.py", line 45, in pprint
    Decompiler(out_file, printlock=printlock,
  File "G:\games_test\rpa_decompiler\decompiler\__init__.py", line 102, in dump
    ast[-1].linenumber == ast[-2].linenumber):
AttributeError: 'Return' object has no attribute 'linenumber'
```

The file does start with `RENPY RPC2`

The ast array looks like this:
```python
[<renpy.ast.Init object at 0x03D6B340>,
<renpy.ast.Init object at 0x03D6B8B0>,
<renpy.ast.Init object at 0x03D6BA48>,
<renpy.ast.Init object at 0x03D6BC40>,
<renpy.ast.Init object at 0x03D6BDD8>,
<renpy.ast.Init object at 0x03D6BFB8>,
<renpy.ast.Init object at 0x03D74148>,
<renpy.ast.Init object at 0x03D742F8>,
<renpy.ast.Init object at 0x03D74490>,
<renpy.ast.Init object at 0x03D74688>,
<renpy.ast.Init object at 0x03D74880>,
<renpy.ast.Init object at 0x03D74A78>,
<renpy.ast.Init object at 0x03D74C70>,
<renpy.ast.Init object at 0x03D74E68>,
<renpy.ast.Init object at 0x03D79088>,
<renpy.ast.Init object at 0x03D79280>,
<renpy.ast.Init object at 0x03D79478>,
<renpy.ast.Init object at 0x03D795E0>,
<renpy.ast.Init object at 0x03D79688>,
<renpy.ast.Init object at 0x03D79730>,
<renpy.ast.Init object at 0x03D797F0>,
<renpy.ast.Init object at 0x03D798F8>,
<renpy.ast.Init object at 0x03D799A0>,
<renpy.ast.Init object at 0x03D79A48>,
<renpy.ast.Return object at 0x03D79AF0>]
```

And this is what I see if I pprint the objects:

```python
#pprint(vars(ast[-1]))
{b'expression': None,
 b'filename': 'game/options.rpy',
 b'linenumber': 221,
 b'name': ('C:\\Users\\Rinko\\Documents\\3DFullGame/game/options.rpy',
           1520959593,
           303),
 b'next': None}

#pprint(vars(ast[-2]))
{b'block': [<renpy.ast.Python object at 0x034A9A90>],
 b'filename': 'game/options.rpy',
 b'linenumber': 221,
 b'name': ('C:\\Users\\Rinko\\Documents\\3DFullGame/game/options.rpy',
           1583316468,
           519),
 b'next': None,
 b'priority': 0}
```

**I know this is supposed to be used with python2 so feel free to ignore it, I'm just curious as to why it's failing.**

**Comment by Bexa2** [comment]
`vars(ast[-1])[b'linenumber']` would be a hack but it would have to be done in many places for all attributes.

**Comment by Bexa2** [comment]
I wonder if Python 3.9's [ast module](https://docs.python.org/3.9/library/ast.html#ast.unparse) would be any useful.

**Comment by Bexa2** [comment]
[Fuck me](https://i.imgur.com/z0G4CZv.jpg), I replaced all `<ast_object>.attribute` with `vars(<ast_object>)[b'attribute']` and all `[not] hasattr(<ast_object>, attribute)` with `b'attribute' [not] in vars(<ast_object>)` and now it turns out that the dict `vars()` returns has b"" string as keys in some games and "" string as keys in others.

**Comment by CensoredUsername** [comment]
Yep, that's the result of ren'py slowly transitioning from py2 to py3. Somewhere along the line all identifiers in the codebase became unicode.

vars(something)[attrname] is rather inefficient btw, iirc it creates a copy of the backing dict. It's easier to just do getattr(something, attrname)

Also some other people have already worked on a py3 port that went pretty far, I just haven't had the time to look over it.

**Comment by Bexa2** [comment]
The problem is that when `vars(ast)` returns a dictionary with b'' keys hasattr(ast, '') will return false, even if the attribute is there and I can't use b'' to check because hasattr rejects it.

```python
print(f"byte string { isinstance(list(vars(ast).keys())[0], bytes) }") # byte string True
print(hasattr(ast, 'linenumber')) # False
print(hasattr(ast, b'linenumber')) # TypeError: hasattr(): attribute name must be string
```

When it doesn't return a dict with b'' keys then it's fine
```python
print(f"byte string { isinstance(list(vars(ast).keys())[0], bytes) }") # byte string False
print(hasattr(ast, 'linenumber')) # True
```

I'll take a look at those python 3 versions to see how they do it.

**Comment by Bexa2** [comment]
Finally "found" what was wrong.

Million thanks to @madeddy

On `magic.py` she changes the default argument to `safe_loads(encoding=)` from `bytes` to `utf-8`.

This can also be set on `unrpyc.py` on `read_ast_from_file` I can add a try catch, try bytes, check for AttributeError then try utf-8

So to get my script working all I had to do was change imports, pass `encoding` to `decompile_rpyc`, `read_ast_from_file` and `deobfuscate.read_ast` and so on until it reaches `safe_loads` it's default value being 'bytes', change `unicode` to `str` and also changed `startswith("RENPY RPC2")` to `startswith(b"RENPY RPC2")`.

I think that's all.

Now moving on to RPG Maker.
