### ISSUE TITLE
about encrypt

### ISSUE THREAD

**Issue by d3af0z** [CensoredUsername/unrpyc#138]
How can I encrypt it?
Is there any way to do it?

**Comment by CensoredUsername** [comment]
What

**Comment by d3af0z** [comment]
i mean. Is there any way to protect rpy files from being decompiled?

**Comment by CensoredUsername** [comment]
well you can make it harder to reverse, but in the end like all DRM schemes you can only make it harder, not impossible for anyone with sufficient knowledge to reverse it.
