### ISSUE TITLE
I hope there is a java version

### ISSUE THREAD

**Issue by 946731djfla** [CensoredUsername/unrpyc#145]
Your project is good, but I hope there is a java version ฅ՞•ﻌ•՞ฅ

**Comment by CensoredUsername** [comment]
Unrpyc is rather bound to python due to ren'py leaning heavily into python itself. Perhaps you could try to use Jython with it?

**Comment by 946731djfla** [comment]
Thank you for your reply, But my of aide Can't run Jython (￣.￣)

**Comment by CensoredUsername** [comment]
Closing this, just get anything that can run python if you need to run this tool. It is only the second most popular programming language on the planet.
