### ISSUE TITLE
Bugs in love Sex

### ISSUE THREAD

**Issue by Alkyos98** [CensoredUsername/unrpyc#147]
When trying to decompile this game which is from renpy 7.5, I get these warnings that you can decompile
![1920350_0a](https://user-images.githubusercontent.com/108735345/177322903-92ed5c09-4b54-4bbb-97ce-619a41ec0d4c.png)

**Comment by CensoredUsername** [comment]
See #146

**Comment by CensoredUsername** [comment]
Actually, this should've been fixed in v1.1.8 a long time ago by commit 2f9810c1
Which was released a couple months before this issue. So I'm just closing this.
