### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xda in position 1: ordinal not in range(128)

### ISSUE THREAD

**Issue by JaydenG420** [CensoredUsername/unrpyc#153]
Issue when launching with un.rpyc in the game directory.

**Comment by rewthing** [comment]
Got this same error message when trying to run against Leap of Faith 1.0c.

**Comment by madeddy** [comment]
Possible reason: Ren'Py 8 is depending on python 3 and unrpyc is so far officially not compatible. Perhaps related to https://github.com/CensoredUsername/unrpyc/issues/92

**Comment by CensoredUsername** [comment]
Please follow the issue submission instructions in the readme. This is much too vague.
