### ISSUE TITLE
Cannot even run unrpyc.py without error

### ISSUE THREAD

**Issue by B01scout** [CensoredUsername/unrpyc#160]
Is this intentional? Same output when using any command. Using Python 3.10.

`E:\unrpyc-1.1.8>python unrpyc.py --help
Traceback (most recent call last):
  File "E:\unrpyc-1.1.8\unrpyc.py", line 49, in <module>
    import decompiler
  File "E:\unrpyc-1.1.8\decompiler\__init__.py", line 22, in <module>
    from util import DecompilerBase, First, WordConcatenator, reconstruct_paraminfo, \
ModuleNotFoundError: No module named 'util'`

![image](https://user-images.githubusercontent.com/74605801/205501915-708b55cb-a100-4213-a9c8-b4b2e82ef48b.png)

**Comment by CensoredUsername** [comment]
Per the readme:

>Usage

>This tool can either be ran as a command line tool, as a library, or injected into the game itself. It requires Python 2.7 to be installed to be used as a command line tool.

Python 3 support will come eventually for the newer generation games. I'm unfortunately rather busy right now.
