### ISSUE TITLE
Is this repo ABANDONED?

### ISSUE THREAD

**Issue by NotAsea** [CensoredUsername/unrpyc#172]
With more game begin using Ren'py 8+, these scripts cannot decompile anymore, i see a lot of people fork and hack around but rarely work, and lack of response from creator, i guess life go on, at lease we still have rpysaveeditor to save the day

**Comment by CensoredUsername** [comment]
It's not abandoned. Life's just been busy and the updates to support Ren'py 7.5/8.0 are much more significant than the small changes between previous versions.

**Comment by FaceCrap** [comment]
Well, you could merge the PR's from maddeddy to save you some work...
