### ISSUE TITLE
Unbreak github actions.

### ISSUE THREAD

**Issue by CensoredUsername** [CensoredUsername/unrpyc#176]
Github actions removed official python 2.7 support. We're still going to be stuck on that for a while though, so best fix that.

**Comment by madeddy** [comment]
I managed a bit of progress in the [yaml file in the py3-port pull](https://github.com/CensoredUsername/unrpyc/pull/159/files#diff-75d65a1ba1cf1acaab2326d7ac67b6e4058cb8f06e0b896c1394bcaaacba1b6a) Maybe its of use.

**Comment by CensoredUsername** [comment]
The python:2.7.18-buster container is recent enough that github actions can do submodule checkouts with it, and old enough it has python 2.7. Using that right now instead of setup-python (until the py3 move). Seems to work and run the tests!
