### ISSUE TITLE
Add explaination and "how to" for translation feature

### ISSUE THREAD

**Issue by madeddy** [CensoredUsername/unrpyc#183]
I didn't really know what it does, nor how to use it and never used it. Nobody ever asked about it AFAIK. Is it even needed? Ren'Py SDK does the same, or not?

I short tests i got just nearly empty files. Needed to read the commit message (822b089) when it was added to get some lead on it.

**Comment by CensoredUsername** [comment]
It was mostly @jackmcbarn's project. Honestly I'm not too sure of it myself. But eh, little cost to maintain it.

**Comment by madeddy** [comment]
I've seen as much in the history.
At least we should make it better accessible. e.g. better doc.

**Comment by CensoredUsername** [comment]
Meh, unless someone wants to use it there's little reason to put extra work into it. We can keep this issue open about it for now.

**Comment by CensoredUsername** [comment]
I think this is fixed now?

**Comment by madeddy** [comment]
It is. Just let this active till the 2.0.2 release. Closing...
