### ISSUE TITLE
AttributeError: 'module' object has no attribute '_loads' with Ren'Py 6.99.12.4.2187

### ISSUE THREAD

**Issue by ghostlyghastly** [CensoredUsername/unrpyc#200]
When trying to decode https://selavi.itch.io/signed-x , which apparently uses Ren'Py 6.99.12.4.2187, This error pops up:

`AttributeError: 'module' object has no attribute '_loads'`

**Comment by madeddy** [comment]
What happens if a user not reads the **readme** where clearly stated is
- which infos we need for a bug report
- which unrpyc version to use for which Ren'Py version
...
```bash
(~/Code/Git/unrpyc)
olli@tty2*blue $ python2 ~/Code/rpy_tools/unrpyc/unrpyc-1.3.0/unrpyc.py /home/olli/.xlib/RPG/_test/SignedX-2.0-pc/game/
Decompiling /home/olli/.xlib/RPG/_test/SignedX-2.0-pc/game/script.rpyc to /home/olli/.xlib/RPG/_test/SignedX-2.0-pc/game/script.rpy...
Decompiling /home/olli/.xlib/RPG/_test/SignedX-2.0-pc/game/tl/german/script.rpyc to /home/olli/.xlib/RPG/_test/SignedX-2.0-pc/game/tl/german/script.rpy...
Decompiling /home/olli/.xlib/RPG/_test/SignedX-2.0-pc/game/screens.rpyc to /home/olli/.xlib/RPG/_test/SignedX-2.0-pc/game/screens.rpy...
Decompiling /home/olli/.xlib/RPG/_test/SignedX-2.0-pc/game/tl/german/common.rpyc to /home/olli/.xlib/RPG/_test/SignedX-2.0-pc/game/tl/german/common.rpy...
Decompiling /home/olli/.xlib/RPG/_test/SignedX-2.0-pc/game/options.rpyc to /home/olli/.xlib/RPG/_test/SignedX-2.0-pc/game/options.rpy...
Decompilation of 5 script files successful
```

**Comment by CensoredUsername** [comment]
@madeddy I get the frustration, but ease up a little. No reason to snark.

That said, @ghostlyghastly please provide a bit more details next time. I think what you did is using an un.rpyc intended for ren'py 8 in a game that is most definitely not running ren'py 8, but what you posted I just really cannot figure it out. Please actually read the documentation.

**Comment by madeddy** [comment]
> ... No reason to snark.

Well, it looks like self-taught English isn't doing me any favors here when I'm trying to be funny. I actually needed to look "snark" up to see of which crime i am charged with.

That said, the info about the Ren'Py version the user provided is correct and it decompiles cleanly with unrpyc v1.3.0 as shown. Also, the original source is even in the archive (*.rpa) included.

**Comment by CensoredUsername** [comment]
>Well, it looks like self-taught English isn't doing me any favors here when I'm trying to be funny. I actually needed to look "snark" up to see of which crime i am charged with.

No worries. Second languages can be hard. Better I informed you of it sounding rude than you not knowing then.

And don't tire yourself on these, I'd normally just write "Please provide additional information", slap them with the "Incomplete bug report" label and carry on with my day.

**Comment by CensoredUsername** [comment]
Closing this for now as no additional information has been provided. Feel free to reopen with extra information if it persists.
