### ISSUE TITLE
Instaliation issues

### ISSUE THREAD

**Issue by Nechochwen-D** [CensoredUsername/unrpyc#201]
Could I get some clarification on what you mean by, "For the script to run correctly it is required for the unrpyc.py file to be in the same directory as the modules directory." I have tried several things and always get errors saying that something or other is missing.

**Comment by CensoredUsername** [comment]
Oh, that is very unclear. I think it's referring to the decompiler directory.

Either way the easiest way to get it to run correctly is to just download a snapshot of the repo, and then run it from the root directory of the repo.

**Comment by Nechochwen-D** [comment]
Likely something to do with my local Python environment then. At least the 1.3.0 version worked after I downloaded it and installed the python2 package from the AUR.

Thanks

**Comment by CensoredUsername** [comment]
oh, AUR.

So the thing about AUR is that basically anyone can put a package in there. And someone at one point put unrpyc in there. I have zero clue who though, it wasn't anyone involved in the project. So I have zero clue what version is even in there.

I think it's using setup.py, I'm not sure if I've actually updated that properly recently. I'll look at it.

**Comment by CensoredUsername** [comment]
Oh huh.

It should just be "clone the repo / download a shapshot of master", move current working directory to it, run `python unrpyc.py`.

Does that not work for you?

**Comment by CensoredUsername** [comment]
Closing this after a month of no response.
