### ISSUE TITLE
Sugar syntax error in the SL2 decompiler

### ISSUE THREAD

**Issue by Lumpy-dev** [CensoredUsername/unrpyc#205]
Hello,

The else statement after this for loop was (I think) to ensure index is never null when the insert is made, but else statements are called only if the loop was ended in a break. This makes the problem still there and ruins the point of the for loop to be there, only an ``index is not null`` in an if statement fixes the bug.
https://github.com/CensoredUsername/unrpyc/blob/79895a10b5b0d93fabc8757aa345981b6bfeb11b/decompiler/sl2decompiler.py#L396-L403

**Comment by Lumpy-dev** [comment]
I found another piece of code having the same problem:
https://github.com/CensoredUsername/unrpyc/blob/db48ec6d7dd31bd215ceb3f120a55aa305aa1c28/decompiler/sl2decompiler.py#L501-L510

Also I found some REALLY bad code there, brackets are missing to create a tuple:
https://github.com/CensoredUsername/unrpyc/blob/db48ec6d7dd31bd215ceb3f120a55aa305aa1c28/decompiler/sl2decompiler.py#L448-L454

This file should really be re-read, I am currently porting the file so that's what I am doing but I may have let some errors slip through.

**Comment by CensoredUsername** [comment]
>but else statements are called only if the loop was ended in a break

>I found another piece of code having the same problem:

That is incorrect. Per the [python documentation](https://docs.python.org/3/tutorial/controlflow.html):

```
In a for loop, the else clause is executed after the loop reaches its final iteration.
In while loop, it’s executed after the loop’s condition becomes false.
In either kind of loop, the else clause is not executed if the loop was terminated by a break.
```

>Also I found some REALLY bad code there, brackets are missing to create a tuple:

Whoops, thanks for the note.

**Comment by Lumpy-dev** [comment]
Sorry, I misread the code I saw to check the if statement behavior. 

It's strange that the other code was kept, I get a really big warning when I saw the line. Should some kind of static analysis be put in place to avoid this kind of issue as testing those cases can be quite difficult? (i.e. in testing or Github Actions)

**Comment by CensoredUsername** [comment]
>Should some kind of static analysis be put in place to avoid this kind of issue as testing those cases can be quite difficult?

If someone cares enough they could. Mind you, this isn't some extreme security code, it's a decompiler for visual novels that I maintain as a hobby. It passes the tests and if issues come up, people can report them. That said, if you know of a decent solution, f feel free to pull request ;)

I saw a post about the thing you're working on a bit earlier btw, fun project. Must've been quite the hassle to port all that

One minor nitpic that I have to make: when porting code between languages, your code still counts as a derivative work. Right now you're claiming copyright over the entire thing as yours and project contributors, while the copyright over ported unrpyc parts should still be from the original contributors. (it should be stated on the top of most of the relevant files, although I might have forgotten it recently).

**Comment by Lumpy-dev** [comment]
After reading the whole code of unrpyc multiple times for my project I think I can do some contributions, when I'll have the time I'll do this (although Python is not the language I am best at).

For the nitpic I already included the license for unrpyc in my LICENSE files so that Flutter would directly pick them up and show them in the UI with the Renpy license too (I ported Renpy code for mapping stuff). I thought adding the copyright at the start of each file would be redundant as I ship my project as one piece but to be sure I'll had a header for the next release.

**Comment by CensoredUsername** [comment]
>After reading the whole code of unrpyc multiple times for my project I think I can do some contributions, when I'll have the time I'll do this (although Python is not the language I am best at).

No worries, I'm happy to have more people looking over the code to begin with.

>I already included the license for unrpyc in my LICENSE files

License and copyright attributions are two different things. Copyright information is for documenting who created something, and licenses are permissions granted by the copyright holder to other folks. You generally need the copyright notice to determine who the license derives from.

I also didn't find it at first because the main LICENSE file doesn't link to it afaik, but I did find it listed in the backend folder. That said, our license (MIT) does state that you are required to include the copyright notice, that is supposed to be above there but missing, with it.

```
The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.
```

>I thought adding the copyright at the start of each file would be redundant

That one is also a bit on me because I seem to have neglected adding the additional significant authors to the main LICENSE file so it's easier to include all of them, I'll update that.

>but to be sure I'll had a header for the next release.

Thanks!

**Comment by CensoredUsername** [comment]
Updated licensing stuff on dev to make it clearer.
