### ISSUE TITLE
Sometimes "elif True" if generated

### ISSUE THREAD

**Issue by Lumpy-dev** [CensoredUsername/unrpyc#222]
In the code it is written:
https://github.com/CensoredUsername/unrpyc/blob/ab65d9fda62837e66d11dcc8a55b12d9d3b09d54/decompiler/__init__.py#L384-L385
I have already found "True" as a ``str`` in a file. But I have also found a "True" as a ``PyExpr`` :
![image](https://github.com/CensoredUsername/unrpyc/assets/157043076/7d9bf032-8574-4895-9e2d-731b9fbc997c)

I found this using the dev branch with a Ren'Py 7 file, so I've changed it to legacy and also found an ``elif True``.

This shouldn't affect the behavior but is a simple thing to change to have something better.

**Comment by CensoredUsername** [comment]
Huh. do you have an example file for this? I have seen no evidence in renpy itself for this. 

Are you sure the source file didn't actually state `elif True`?

**Comment by Lumpy-dev** [comment]
This could have been something generated with a specific version RenPy as I found this file by downloading a bunch of random games, decompiling the RPAs and comparing both implementations.

So I dug a bit deeper to find out and conveniently, the original creator of this game left the original RPY files in the final game and I did found an ``elif True`` statement and then an ``else`` statement. Maybe they wanted to make this branch as some sort of comment? In that case UnRPYC did not make any mistake so I retested without my change and it seems like the behavior is the same... Also with the 14 large games I tested this is the single time this happens.

Maybe we could still change the behavior so that the original ``else`` branch is put with comments and ``elif True`` is replaced with ``else`` to avoid confusion?

This problematic file (original and compiled):
[group_event_dinner_time_2_dinner.zip](https://github.com/CensoredUsername/unrpyc/files/15075366/group_event_dinner_time_2_dinner.zip)

**Comment by CensoredUsername** [comment]
>Maybe we could still change the behaviour so that the original else branch is put with comments and elif True is replaced with else to avoid confusion?

The goal of unrpyc is to replicate the input files as exact as possible. If the input file contained `elif True` followed by `else` then we should emit the same, even if it is something silly from the original author. So I don't think anything needs to be changed here.

And yeah, probably they were just trying some things and didn't want to delete the original branch just yet.
