### ISSUE TITLE
ModuleNotFoundError: No module named 'renpy'

### ISSUE THREAD

**Issue by Ronzan** [CensoredUsername/unrpyc#225]
Hello,

I'm probably just missing something simple, but I cannot run unrpyc.py.
I cloned the repo and updated Python 3 today.
I do and get the following:
![image](https://github.com/CensoredUsername/unrpyc/assets/4838857/6c0e475a-ec66-407a-908c-345a4218b5c3)

Any clues?

Thanks

**Comment by CensoredUsername** [comment]
That's very curious. Thank you for the thorough report. Might be something with python 3.12. Can you test with 3.9/3.10 by any chance?

**Comment by CensoredUsername** [comment]
Edit: I can reproduce this on 3.12.3. Something's breaking in the import faking system likely.

**Comment by CensoredUsername** [comment]
Yep, `MetaPathFinder.find_module` backwards compat got removed, that was causing the error.

Implemented the new `MetaPathFinder.find_spec` and now everything works again. You can check it out on the `dev` branch.

I also added python 3.12 to the unit tests, so we don't get caught by such changes in the future.

**Comment by Ronzan** [comment]
Awesome, thanks @CensoredUsername !
I grabbed the dev branch and it is working on my system now.

Sorry I couldn't test it before now, I'm in a different time zone I guess :)
Thank you for you work here and fast response, much appreciated.
