### ISSUE TITLE
Cannot import as a library; fails at importing 'renpy'

### ISSUE THREAD

**Issue by drunkromanian** [CensoredUsername/unrpyc#230]
Whenever I import `unrpyc.decompiler` from outside the unrpyc directory, it gives the following traceback:
```
Traceback (most recent call last):
  File "/home/bulb/Documents/Projects/Python/Qt/Dossier/main.py", line 6, in <module>
    from src.utils import game_assets
  File "/home/bulb/Documents/Projects/Python/Qt/Dossier/src/utils/game_assets.py", line 6, in <module>
    from src.unrpyc.decompiler.renpycompat import renpy
  File "/home/bulb/Documents/Projects/Python/Qt/Dossier/src/unrpyc/decompiler/__init__.py", line 24, in <module>
    from .renpycompat import renpy
  File "/home/bulb/Documents/Projects/Python/Qt/Dossier/src/unrpyc/decompiler/renpycompat.py", line 26, in <module>
    magic.fake_package("renpy")
  File "/home/bulb/Documents/Projects/Python/Qt/Dossier/src/unrpyc/decompiler/magic.py", line 665, in fake_package
    return __import__(name)
           ^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'renpy'
```

I am using unrpyc v2.0.1, and I have also tried importing it with bpython and it works somehow, just not in my scripts. My repository is over at [drunkromanian/dossier](https://github.com/drunkromanian/dossier/blob/main/src/utils/game_assets.py)
This is my first actual project, so I am sorry if my code sucks 🙃 Any insights or suggestions would be greatly appreciated!

**Comment by drunkromanian** [comment]
Just found out the reason why it worked in bpython is that it wasn't run in my virtual environment. Is there a way to run this while in a venv?

**Comment by CensoredUsername** [comment]
Likely duplicate of #225. The cause is some changes to the import machinery in 3.12. You can use the dev branch until I make a new release to work around it.

**Comment by CensoredUsername** [comment]
huh, that shouldn't be an issue.

I also need more details than just that. Could you post info as described in the README in the section on issue reports?

**Comment by drunkromanian** [comment]
Well, I am using the dev unrpyc branch on Ren'Py 6.99.12 (base DDLC) and I am trying to decompile every script in the scripts.rpa archive (which is already extracted with rpatool). 
When I was using the stable unrpyc release it was also failing at importing the decompiler, but I was able to solve it by importing the decompiler before unrpyc like so: `from src.unrpyc import decompiler, unrpyc`. Now that doesn't work. You can still import the decompiler manually without any errors, but when you try to import unrpyc it fails at importing the decompiler.
The traceback I get is pretty expected: 
```
Traceback (most recent call last):
  File "/home/bulb/Documents/Projects/Python/Qt/Dossier/main.py", line 6, in <module>
    from src.utils import game_assets
  File "/home/bulb/Documents/Projects/Python/Qt/Dossier/src/utils/game_assets.py", line 6, in <module>
    from src.unrpyc import unrpyc
  File "/home/bulb/Documents/Projects/Python/Qt/Dossier/src/unrpyc/unrpyc.py", line 44, in <module>
    import decompiler
ModuleNotFoundError: No module named 'decompiler'
```

**Comment by drunkromanian** [comment]
![image](https://github.com/CensoredUsername/unrpyc/assets/88433044/60431ff4-8b41-4b98-912d-a78cb589758f)
I also slightly changed the imports in game_assets.py, but I doubt that info's any useful.

**Comment by CensoredUsername** [comment]
ah, yeah.

Unrpyc isn't really meant to be used by importing it. This isn't really supported right now. unrpyc.py is the front-end command line tool. Decompiler contains the decompilation logic.

**Comment by drunkromanian** [comment]
Copied over the read_ast_from_file() and decompile_rpyc() functions over to another file, imported that and now it works! Thanks for everything 😅
