### ISSUE TITLE
unrpyc gives error

### ISSUE THREAD

**Issue by AlexMoun** [CensoredUsername/unrpyc#238]
I get this error when converting rpyc to rpy. I tried try harder mode, same error.

Decompiling C:\Users\Administrator\Desktop\TheList-0.11-pc\game\scripts\common.rpyc to C:\Users\Administrator\Desktop\TheList-0.11-pc\game\scripts\common.rpy...
Error while decompiling C:\Users\Administrator\Desktop\TheList-0.11-pc\game\scripts\common.rpyc:
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\TheList-0.11-pc\deobfuscate.py", line 287, in read_ast
    data = extractor(f, 1)
  File "C:\Users\Administrator\Desktop\TheList-0.11-pc\deobfuscate.py", line 83, in extract_slot_rpyc
    raise ValueError("Broken slot entry")
ValueError: Broken slot entry

I've attached the file below.
[common.zip](https://github.com/user-attachments/files/16740086/common.zip)

**Comment by CensoredUsername** [comment]
Unrpyc isn't able to read that file. It's header is incorrect, stating the file is longer than it actually is. Are you sure that's the full file?

If the game still runs fine, then likely someone messed with the engine in a way unrpyc cannot read. There's little I can do about a specific game messing with the engine, you'll have to figure out what they did with it.

**Comment by AlexMoun** [comment]
> Unrpyc isn't able to read that file. It's header is incorrect, stating the file is longer than it actually is. Are you sure that's the full file?
> 
> If the game still runs fine, then likely someone messed with the engine in a way unrpyc cannot read. There's little I can do about a specific game messing with the engine, you'll have to figure out what they did with it.

yes full file. obviously I tried a lot but I couldn't convert it to rpy. something has been changed

**Comment by CensoredUsername** [comment]
I don't support custom engine tweaks, so aside from some pointers in the right direction, I can't help you there.
