### ISSUE TITLE
Error decompiling the .rpyc format

### ISSUE THREAD

**Issue by 1666059026** [CensoredUsername/unrpyc#239]
2024-11-29 00:05:18 UTC
Windows-10-10.0.19041
Ren'Py 8.3.2.24090902

https://mega.nz/file/SN5V0ZpK#sVg4RUZTjoB320Ib1sfOthWiyLFgFwxMcALhgVabWPc

**Comment by CensoredUsername** [comment]
https://github.com/CensoredUsername/unrpyc?tab=readme-ov-file#when-making-an-issue-report

**Comment by madeddy** [comment]
Was bored so i tested this without any problems. Problem must on the user system or a mistake, so it could maybe be closed.
My run from Kubuntu 22.04.5: [terminal_output.txt](https://github.com/user-attachments/files/18260010/terminal_output.txt)

**Comment by CensoredUsername** [comment]
That, and no response for a month on providing enough information in the original report definitely merits closing this one.
