### ISSUE TITLE
Whitespace inside parentheses causes additional sets of parentheses to be generated

### ISSUE THREAD

**Issue by jackmcbarn** [CensoredUsername/unrpyc#24]
Given this original source:
```
screen testScreen:
    modal True
    imagemap:
        hotspot (0, 100, 500, 50):
            clicked Play("foo","foo.ogg")
        hotspot (100,100,500,50):
            clicked Play("bar","bar.ogg")
        hotspot (200,100,500,50):
            clicked Play("baz", "baz.ogg")
```
When compiled and decompiled, this is the result:
```
screen testScreen:
    modal True
    imagemap:
        hotspot ((0, 100, 500, 50)):
            clicked Play("foo","foo.ogg")
        hotspot (100,100,500,50):
            clicked Play("bar","bar.ogg")
        hotspot (200,100,500,50):
            clicked (Play("baz", "baz.ogg"))
```
Note that the parentheses that contained whitespace in the original code have been doubled in the result.

**Comment by CensoredUsername** [comment]
The fix for screen language 2 was easy since after taking a closer look, it seemed the guarding there using parenthesis was an unnecessary leftover from screen language 1. And in screen language 1 I've fixed the problem by analyzing if ren'py would process the keyword argument correctly.
