### ISSUE TITLE
SL1 missing support for "image" and "on" statements

### ISSUE THREAD

**Issue by jackmcbarn** [CensoredUsername/unrpyc#40]

**Comment by CensoredUsername** [comment]
I know  about it missing support for the on statement, but there's no screen language "image" statement. If you use an image it's the "add" statement which is used, which I'm pretty sure is supported.

**Comment by jackmcbarn** [comment]
There's an image statement. See https://github.com/renpy/renpy/blob/6.17.7.521/renpy/screenlang.py#L717

**Comment by CensoredUsername** [comment]
It exists, but it's not documented. typical. 

Then again that goes for a lot more things in ren'py.
