### ISSUE TITLE
An error occured while decompiling the first script of Katawa Shoujo

### ISSUE THREAD

**Issue by RazoRTR** [CensoredUsername/unrpyc#44]
First of all, thank you for this wonderful tool. It works really good. But, when I try to decompile the first script file of Katawa Shoujo, I get an error.
![ks](https://cloud.githubusercontent.com/assets/4212660/8593928/e5a58372-2644-11e5-8d16-a468527c56de.png)

In fact, even if it gives me this error, it also decompiles some of the file, but incomplete; only till when it comes to the first menu label.
I've tried to decompile German, Japanese, Russian etc. versions of the same file as well, but it always gives me the same error.
My operating system is Windows 8.1 64-bit, and I've installed Python 2.7 as stated in the Read Me file.
Sadly, I'm not that experienced in programming, and Python, so I don't know how to solve it. :(

**Comment by CensoredUsername** [comment]
The issue should be solved now, backwards compatibility was accidentally forgotten somewhere.

**Comment by RazoRTR** [comment]
Yes, now it decompiled the file perfectly. Thanks for the hard work! ^^
