### ISSUE TITLE
Support the rpyc2 format

### ISSUE THREAD

**Issue by CensoredUsername** [CensoredUsername/unrpyc#45]
Starting from ren'py 6.99.5, the .rpyc save format has changed significantly. This format can be distinguished by a new header in the files.

Total of things that have been altered:

New header: RENPY RPC2.
New archive format. The header is followed by a table of slot/offset/length pointing to locations in the file. These locations contain the compressed pickled AST.
Way the AST is pickled. Now uses \_\_new\_\_ instead of \_\_setstate\_\_. I'm not sure if this is an issue.
Currently the format is used in a simple way. slot 1 contains the old-fashioned rpyc data, slot 2 contains the same data with static transformations (like translation) applied.

**Comment by ffleader1** [comment]
![image](https://cloud.githubusercontent.com/assets/15016720/10341103/876d4070-6d3d-11e5-9b36-71898efd9cb6.png)
I got this error. Could it be due to newer ren'py version?

**Comment by CensoredUsername** [comment]
This might very well be the case. The changes necessary to decompile this format are still on the dev branch, you could test it with this if you want.

**Comment by ffleader1** [comment]
Steamgirl on lemasoft forum helped me. By deleting the first 46 characters, the decompiler works!

**Comment by CensoredUsername** [comment]
It should work fine now, closing this.
