### ISSUE TITLE
Translate while decompiling

### ISSUE THREAD

**Issue by jackmcbarn** [CensoredUsername/unrpyc#49]
Games are occasionally written in languages other than English, and English is then supported just as any other translated language. This works fine in the games, but it makes it really hard to understand the .rpy, since it's all in the source language. It would be nice if there were a way to load the translations into unrpyc, such that it would append the translated text in a comment after the lines, or maybe even replace the original text with translated text.

**Comment by CensoredUsername** [comment]
As this is currently done on the dev branch with no bugs remaining as far as I can tell, shall we push this to master?

**Comment by jackmcbarn** [comment]
Agreed. Pushed.

**Comment by Epicyon** [comment]
I apologize for posting this on an ancient closed issue, but what would the command line look like to make use of the translate while decompiling?   Every permutation I've tried with -T, -t, -l, don't seem to be right, and I assume I'm just using the tool incorrectly.
