### ISSUE TITLE
Unable to extract rpyc files with latest un.rpyc

### ISSUE THREAD

**Issue by adaw9** [CensoredUsername/unrpyc#50]
Hi,

I tried to extract some rpyc files these days but it seems like something goes wrong. 
I would appreciate if you can help me fix this problem. Thanks.

Please find the rpyc files and unrpyc log at
https://www.dropbox.com/s/2c8pnvx9fpuyphj/rpyc%20files.rar?dl=0
https://www.dropbox.com/s/wrkr751mghmouyt/unrpyc.log.txt?dl=0

Thanks!

**Comment by CensoredUsername** [comment]
Hey,

Looks like I made a small error in the new file format support when porting it to un.rpyc.

[Try this version](https://github.com/CensoredUsername/unrpyc/releases/tag/v1.0.6), it should fix the problem.

Thanks for the log files, they made it really easy to diagnose.

**Comment by adaw9** [comment]
Thank you!

It really helps!
