### ISSUE TITLE
Unknown SL2 displayable: (<class 'renpy.sl2.sldisplayables.sl2vpgrid'>, 'vpgrid')

### ISSUE THREAD

**Issue by makc-ar** [CensoredUsername/unrpyc#52]
Example .rpyc: https://mega.nz/#!I1ZEAQiK!nAh4YiNlAljv1oYHEmegNNhS9JXQUDaaD9ZeZTfNHpg

errors.txt:
I'm sorry, but errors were detected in your script. Please correct the
errors listed below, and try again.
File "game/script.rpy", line 581: The pass statement cannot be used as a container for the has statement.
    has pass 
            ^
Ren'Py Version: Ren'Py 6.99.10.1227

**Comment by jackmcbarn** [comment]
Try the dev branch. It should be fixed there now.

**Comment by makc-ar** [comment]
@jackmcbarn
Thanks a lot!
