### ISSUE TITLE
Keep getting 'Permission Denied'

### ISSUE THREAD

**Issue by sofieamelia** [CensoredUsername/unrpyc#53]
Hi there,
I'm trying to use unrpyc, I just keep getting the same ''Permission Denied" after every file I try to extract. I'm obviously doing something wrong, don't suppose you could give me a step-by-step for a noobie?
I would really appreciate it, thank you.

**Comment by jackmcbarn** [comment]
Can you upload a screenshot of exactly what you're doing?

**Comment by sofieamelia** [comment]
Thanks for your fast reply! Not at computer atm, but from my head I did these steps: downloaded unrpyc moved to folder with my .rpyc I want to extract. Open unrpyc with python 2.something, and then drag and dropped the files I wanted to extract pressed enter and then up pops "permission denied". I bet I've done it completely wrong. Sorry I'm a newbie. Also on Mac if that makes a difference?

**Comment by jackmcbarn** [comment]
You can't run unrpyc by opening it from Finder. Are you familiar with Terminal? If you are, start a terminal in the unrpyc directory and run "python2 unrpyc.py _whatever_.rpyc". If not, you'd probably better off using the "un.rpyc" build. To do this, download the latest un.rpyc file from https://github.com/CensoredUsername/unrpyc/releases and put it in the same directory as the .rpyc files that you want to decompile. Then start the game, and it will decompile all of them into the same directory. Let me know if either of those solutions work.

**Comment by sofieamelia** [comment]
That worked! I'm such an idiot, it was that simple. Thank you so much, you're awesome!!
