### ISSUE TITLE
Finish travis/bintray stuff

### ISSUE THREAD

**Issue by jackmcbarn** [CensoredUsername/unrpyc#58]
- [ ] Make the Bintray upload not error out for tags or game branches https://travis-ci.org/CensoredUsername/unrpyc/builds/190078228
- [ ] Add a separate package for releases, for above
- [ ] Add the files to the download list travis-ci/dpl#565
- [ ] Link to Bintray from README.md
- [x] Add a test .rpyc file and make sure it becomes its matching .rpy file
- [ ] Maybe make it test actually round-tripping with Ren'Py instead of putting rpyc files in git
- [ ] Some sort of test for dumping

**Comment by CensoredUsername** [comment]
This issue has been outdated for several years as we moved to github actions.
