### ISSUE TITLE
Gaben needs the command to compile files again

### ISSUE THREAD

**Issue by TheGaben47** [CensoredUsername/unrpyc#59]
# GabenIsn'tTheSmartestGuyAround
I can't seem to find anything or anyway to compile my decompiled files,
Hope you can help me?

I'm bored- for now, so other than that:
"Prepare your wallet. And watch for the best time passing TV ever." 
[http://gaben.tv/](url)

**Comment by CensoredUsername** [comment]
Ren'py compiles .rpy files to .rpyc files  automatically. There's no need to compile them yourself.
