### ISSUE TITLE
"Love ribbon" rpyc error (no script)

### ISSUE THREAD

**Issue by Ria-kon** [CensoredUsername/unrpyc#60]
6 of 33 — done
27 of 33 — No script files given error

for example, this one:
https://www.dropbox.com/s/dt53bv7g0ntba5l/01_first%20meeting.rpyc?dl=0

**Comment by jackmcbarn** [comment]
That file decompiles fine for me. Can you post a screenshot that includes both the command you type and the error?

**Comment by jackmcbarn** [comment]
I suspect that the issue may be due to the way you're passing the filename as a parameter, since there's a space in it. You should wrap the name in quotes. Also, I just pushed a commit that improves the errors you get in your situation. Try it and let me know what it does.

**Comment by Ria-kon** [comment]
```
File not found: 01_first
File not found: meeting.rpyc
No scripts file to decompile
```
Well, i think main problem in my bat (that seculates filename by spaces).

**Comment by jackmcbarn** [comment]
Yes, that makes it clear that the problem is that your bat file isn't quoting the names properly. Note that you no longer need to specify each file at all, though. If you instead specify the directory, unrpyc will decompile all of the .rpyc's in it and in its subdirectories.

**Comment by Ria-kon** [comment]
Okay, thanks
