### ISSUE TITLE
Problem with the "unrpyc.py" line 89

### ISSUE THREAD

**Issue by Dorifor** [CensoredUsername/unrpyc#62]
Hello, i'm sorry that I need your help this late (few years later) but I have a problem : 

I installed Python 3.6.1 and I enter this command in a normal command terminal : 

C:\Users\Administrateur\AppData\Local\Programs\Python\Python36-32\python.exe unrpyc.py script-a1-friday_FR.rpyc

after that, I have a error message : 
C:\Users\Administrateur\AppData\Local\Programs\Python\Python36-32\python.exe unrpyc.py script-a1-friday_FR.rpyc
  File "unrpyc.py", line 89
    print "Decompiling %s to %s..." % (input_filename, out_filename)
                                  ^
SyntaxError: invalid syntax

I searched in the file unrpyc.py with Notepad++ but I'm not really good at Python so I need help, please.

**Comment by Dorifor** [comment]
Okkkkkkkkkk I find what was the problem ! 

I just installed the wrong version of Python ^^' 

But now with the 2.7 version, it works !

**Comment by CensoredUsername** [comment]
Ok then.
