### ISSUE TITLE
"Unknows AST node <class 'renpy.ast.TranslateEarlyBlock" in Fatal Twelve Demo

### ISSUE THREAD

**Issue by Ria-kon** [CensoredUsername/unrpyc#63]
(this is *.rpyc hided under *.pdf)
[script.pdf](https://github.com/CensoredUsername/unrpyc/files/1082540/script.pdf)

**Comment by CensoredUsername** [comment]
Looks like that node was just never added in together with the rest of the translate nodes (since it's so rarely used). Should have a fix soon.

**Comment by CensoredUsername** [comment]
A fix is available on the dev branch.

**Comment by Ria-kon** [comment]
Working good for now. Closed
