### ISSUE TITLE
Myth "COULD NOT DECOMPILE: Unknown SL2 displayable: (<class 'store.ScrollbarButton'>, 'scrollbarbutton')"

### ISSUE THREAD

**Issue by Ria-kon** [CensoredUsername/unrpyc#64]
In 2 files:
1. [readback.pdf](https://github.com/CensoredUsername/unrpyc/files/1118583/readback.pdf)
2. [chara_chart.pdf](https://github.com/CensoredUsername/unrpyc/files/1118589/chara_chart.pdf)

**Comment by CensoredUsername** [comment]
Looks like we didn't handle user-defined displayables yet. Unfortunately, I've only been able to add a workaround as the actual name of the user-defined screen language statement is lost in the actual screen language compilation and there is no way we can figure out based on the individual file what the actual name is. Therefore for now we print a warning when encountering one and guess that the statement name matches the given style name. It's the best we can do unfortunately, this is the one feature in .rpyc's that isn't properly decompileable.

**Comment by Ria-kon** [comment]
Because in myth this is already added in separated file (i dont see it for first time) and now no need to edit file — close
