### ISSUE TITLE
"rpymc"->"rpym" Ren'Py script module support

### ISSUE THREAD

**Issue by Uzume** [CensoredUsername/unrpyc#67]
Does un.rpyc intentionally not support decompiling Ren'Py script modules loaded with [renpy.load_module](https://github.com/renpy/renpy/blob/26c7a2b2d3f114d0b29b37e537b8c4fec860f06b/renpy/exports.py#L2254) (not to be confused with [renpy.loader.load_module](https://github.com/renpy/renpy/blob/26c7a2b2d3f114d0b29b37e537b8c4fec860f06b/renpy/loader.py#L699))? Information on this can be found in its [documentation](https://www.renpy.org/doc/html/other.html#renpy.load_module) and the older [wiki](https://renpy.org/wiki/renpy.load_module).

I ask this, because I could not find this support in un.rpyc (although I could not see why unrpyc.decompiler would not support such) and according a quick blame search in Ren'Py source, it has supported such for upwards of 10-12 years (I did not attempt to dig deeper; the codebase has moved around and it is quite possible such modules were supported even earlier in Ren'Py).

It should be noted that [renpy.script](https://github.com/renpy/renpy/blob/26c7a2b2d3f114d0b29b37e537b8c4fec860f06b/renpy/script.py) treats rpy/rpyc scripts and rpym/rpymc script modules very similarly and more specifically [renpy.script.load_file](https://github.com/renpy/renpy/blob/26c7a2b2d3f114d0b29b37e537b8c4fec860f06b/renpy/script.py#L542) handles [rpy/rpym](https://github.com/renpy/renpy/blob/26c7a2b2d3f114d0b29b37e537b8c4fec860f06b/renpy/script.py#L544) and [rpyc/rpymc](https://github.com/renpy/renpy/blob/26c7a2b2d3f114d0b29b37e537b8c4fec860f06b/renpy/script.py#L610) in exactly the same way.

**Comment by CensoredUsername** [comment]
I honestly forgot script modules were actually a thing, and nobody has ever requested support for it (probably because almost nobody uses them except for the engine itself).

I'll look into it.

**Comment by CensoredUsername** [comment]
I've added support in 381cfa5, will merge it after some testing.

**Comment by Uzume** [comment]
There is a typo in the above patch; see the comment on the commit.

**Comment by CensoredUsername** [comment]
The typo has been fixed on dev.

**Comment by Uzume** [comment]
I am assuming you are referring to ddc961c. That seems to have been fixed on innocent_witches branch but not on dev branch.

**Comment by CensoredUsername** [comment]
Whoops, worked on both at the same time and forgot to also push my local dev branch. It should be correct now.

**Comment by CensoredUsername** [comment]
Since no further replies came in I'll assume this is fixed.
