### ISSUE TITLE
Support for v7.0?

### ISSUE THREAD

**Issue by hanakou** [CensoredUsername/unrpyc#73]
v7.0 has introduced a "new layered image system," and so anything that's defined under the "layeredimage" statement is not decompiled.
Only "init layeredimage [name_of_image]:"  is detected. What comes after the init block is blank/empty.

**Reference:**
https://www.renpy.org/dev-doc/html/layeredimage.html#layered-images
https://www.renpy.org/doc/html/changelog.html

**Comment by CensoredUsername** [comment]
Thanks for the notification! I'll investigate the necessary changes.

**Comment by CensoredUsername** [comment]
As of v1.0.11 we should support all ren'py 7.0 features.
