### ISSUE TITLE
RenPy's new "use expression" feature not working with unrpyc decompiled scripts

### ISSUE THREAD

**Issue by madeddy** [CensoredUsername/unrpyc#86]
More bugs with the current dev-branch. It gets stranger with every try:
Renpy errors.txt:

```
I'm sorry, but errors were detected in your script. Please correct the
errors listed below, and try again.


File "game/scripts/core/user_interface/computer/app/email.rpy", line 31: expected 'word' not found.
    use 'pc_app_email_' + app.tmp.open
        ^

File "game/scripts/core/user_interface/computer/desktop.rpy", line 18: end of line expected.
    use app.screen(app)
           ^

File "game/scripts/core/user_interface/popup/proxy.rpy", line 24: end of line expected.
    use spec[0](*spec[1:])
            ^

Ren'Py Version: Ren'Py 7.3.5.606
Wed Feb  5 18:31:02 2020
```

The whole set of original *.rpyc:
[rpyc_scripts.zip](https://github.com/CensoredUsername/unrpyc/files/4171074/rpyc_scripts.zip)

**Comment by CensoredUsername** [comment]
Looks like it's using the new "use expression" feature of ren'py, should be an easy fix.

**Comment by CensoredUsername** [comment]
Should be fixed on the dev branch as well.

**Comment by bacsojin1102** [comment]
yes.
i had tested with Summertime Saga 0.19.5.
It's fixed.

**Comment by madeddy** [comment]
No.
I get again a bug if i run the game with the decompiled scripts: 
[traceback.txt](https://github.com/CensoredUsername/unrpyc/files/4180768/traceback.txt)

**Comment by CensoredUsername** [comment]
Ah I see, it is supposed to be parsed as spec[0] holding the name, and (*spec[1:]) being the argument list for it.

**Comment by CensoredUsername** [comment]
Should be fixed now as well.

**Comment by madeddy** [comment]
Super!
Yeah, thats a strange construct there in  RenPy. Needing 'pass' as sep... 

I test this now and get then back. Hopefully thats all then with the changes from RenPy which breaked all this.

**Comment by madeddy** [comment]
There a re no easily recognizable exceptions anymore like before, but the test game is not payable anymore for me.
Somehow the decompiling breaks now the game state. Ingame options like map or menu choices not reachable or available anymore. Some game decisions are forgotten now. I "think" the game variables could be affected by this. Its true for a new started game and also if one uses savegames.

**Comment by CensoredUsername** [comment]
>Yeah, thats a strange construct there in RenPy. Needing 'pass' as sep...

It's required to resolve the syntactical ambiguity of the screen name being a python expression as well as the args list being a parenthesis-delimited list of expressions. It has to be there due to the lack of properly delimited python expressions in renpyscript syntax.

>Somehow the decompiling breaks now the game state. Ingame options like map or menu choices not reachable or available anymore. Some game decisions are forgotten now or not triggered at all. I "think" the game variables could be affected by this. Its true for a new started game and also if one uses savegames.

That sounds weird, but I need more information to start from. If you can figure out a location where it breaks I can look at it in a new issue, but for now I'm closing this one as the specific problems here have been fixed.
