### ISSUE TITLE
Choice boxes doesn't appear after script decompilation

### ISSUE THREAD

**Issue by TakaiSaisei** [CensoredUsername/unrpyc#89]
Seems that decompiler generating incorrect code - instead of in-game choice boxes I'm getting just exceptions. There are 2 tracebacks (I think they're almost the same) - 1st from welcome screen asking you to select a language, 2nd from the gameplay itself.
[traceback1.txt](https://github.com/CensoredUsername/unrpyc/files/4245561/traceback1.txt)
[traceback2.txt](https://github.com/CensoredUsername/unrpyc/files/4245563/traceback2.txt)

If I understood correctly. the problem located in screens.rpy, so there are original screens.rpyc also.
https://drive.google.com/open?id=1YHwriKbwcaDGHi9sKkEPAun-GX37zBCF

Game: The Expression Amrilato (RenPy 7.3.2.320)

**Comment by CensoredUsername** [comment]
Could you also send me game/splash.rpy? The issue is with arguments being passed to the choice screen, which seem to not be there.

**Comment by TakaiSaisei** [comment]
Ugh, sorry, I'd checked it more carefully, decompilation of screens.rpyc have nothing with it. I get exception on welcome screen after decompilation of splash.rpyc, exception in 1st chapter after decompilation of am001a.rpyc, in 2nd chapter after am002a.rpyc and so on.

*.rpyc - original, *.rpy - decompiled with latest version of unrpyc

[splash.rpyc](https://drive.google.com/open?id=1YBmbkoLOJ-rxrQCclu6ApFkJ3RAngaey)
[splash.rpy](https://drive.google.com/open?id=1_EWCAZtWaDDKwc7wYve6mAi-Efk2_e3s)
[am001a.rpyc](https://drive.google.com/open?id=1FP3B_vO-mIEyq6HaSSk13nf6UYgI78dw)
[am001a.rpy](https://drive.google.com/open?id=1K6FojYpA6taMUobr4cIQKuYEyVMtT6y5)

In am001a.rpy choice screen appears at 713 string.

**Comment by CensoredUsername** [comment]
Looks like the issue is that we don't support menu arguments / menu item arguments yet. Should be an easy fix.

**Comment by CensoredUsername** [comment]
There's a fix available on the dev branch, could you test it and confirm everything works?

**Comment by TakaiSaisei** [comment]
Yep, it's okay now, thank you.

**Comment by CensoredUsername** [comment]
Just a headsup, the dev release didn't support menu arguments themselves yet, which in the new release are also reported. Your rpyc file also used those.
