### ISSUE TITLE
COULD NOT DECOMPILE: Unknown AST node

### ISSUE THREAD

**Issue by RbElli0t** [CensoredUsername/unrpyc#93]
Hi, 
I tried to decompile a **.rpyc** file. but after decompiling, in **.rpy** file it says

**pass # <<<COULD NOT DECOMPILE: Unknown AST node: <class 'store.locations.CallLocation'>>>>**

Problem with un.rpyc tool or scripts ? This .rpyc files extracted from .rpa with rpatool 

Complete Decompiled Script file: https://pastebin.com/Si1LntMC

**OS:** Linux

**Comment by CensoredUsername** [comment]
See #70 . This isn't an issue unrpyc can handle in a portable way.

**Comment by RbElli0t** [comment]
Thanks :)
