### ISSUE TITLE
The problem with Decompilation Big?? rpyc file

### ISSUE THREAD

**Issue by Thegameing** [CensoredUsername/unrpyc#94]
I have a 175kb Rpyc file, after the Decompilation the file being smaller to 95kb and some line are disappear.

Ren'Py 6.99.14.1.3218
Python 2.7

**Comment by CensoredUsername** [comment]
The size difference doesn't say anything, it's quite common for rpyc files to be larger than the original rpy files. And you're going to need to be a lot more detailed than "some line are disappear" for me to help you.

**Comment by jackmcbarn** [comment]
What game was this? Can you attach the original rpyc file?

**Comment by CensoredUsername** [comment]
Closing this due to lack of response.
