### ISSUE TITLE
Handle "as" and "tag" better

### ISSUE THREAD

**Issue by jackmcbarn** [CensoredUsername/unrpyc#98]
Currently, we always put "as" and "tag" as the first two lines inside of "screen", even if line numbers imply this isn't where they went. Also, when we're sure we're decompiling older versions of Ren'Py, we should still put "tag" on the same line as "screen".

**Comment by CensoredUsername** [comment]
While it's rarely used in practice, upgrading the engine of an already released game is still something that ren'py tries to support. I'm less concerned about line-number accuracy (it's nice for tests and to look at but minor offsets aren't a problem) than I'm about getting random issue reports about decompiled games giving errors. It should be an opt-in choice.

**Comment by CensoredUsername** [comment]
Unrelatedly though, long time no see, nice to see you active again ;)

**Comment by jackmcbarn** [comment]
> upgrading the engine of an already released game is still something that ren'py tries to support

They do? Isn't the response at renpy/renpy#1860 itself evidence that they don't?

> I'm less concerned about line-number accuracy (it's nice for tests and to look at but minor offsets aren't a problem) than I'm about getting random issue reports about decompiled games giving errors. It should be an opt-in choice.

Fair enough; changed in e42f460.

> Unrelatedly though, long time no see, nice to see you active again ;)

It's nice to be back! :)

**Comment by CensoredUsername** [comment]
>They do? Isn't the response at renpy/renpy#1860 itself evidence that they don't?

That's a problem with upgrading the engine as developer with *.rpy files present. Upgrading when *.rpyc files are present wouldn't cause that as it's an error in the stage of compiling *.rpy to *.rpyc. 

I'm in favour of these kinds of workarounds when the new syntax breaks the .rpy in the old engine but if there's a syntax that works in both I'd say stick to that.

>It's nice to be back! :)

Glad to have you!

**Comment by CensoredUsername** [comment]
Closing this as it was fixed 3 years ago I think.
